### set log levels:debug, info, warn, error ###
# debug 為一般程序測試時用
# info 為一般必需的遊戲記錄用
# warn 需要強烈注意的信息
# error 程序異常
log4j.rootLogger = info,STDOUT,E
log4j.logger.net.world.function.ChattingSystem = info,CHAT
log4j.logger.net.world.function.TradeSystem = info,ITEM
log4j.logger.net.world.instance.inventory.function.Enchant = info,ITEM
log4j.logger.net.world.instance.MonsterInstance = info,ITEM
log4j.logger.net.world.instance.ItemInstance = info,ITEM
log4j.logger.net.world.instance.ShopInstance = info,ITEM
log4j.logger.net.world.instance.DwarfInstance = info,ITEM
log4j.logger.net.world.instance.inventory.PcInventory = info,ITEM
log4j.logger.net.util.SpeedHackChecker = info,SPEED
log4j.logger.net.check.CheckSpeed = info,SPEED
log4j.logger.net.database.AccountTable = info,LOGINOUT
log4j.logger.net.network.client.C_RequestCharselete = info,LOGINOUT
log4j.logger.net.database.CharacterTable = info,LOGINOUT
log4j.logger.net.network.client.C_Logins = info,LOGINOUT
log4j.logger.net.network.client.C_CharacterCreate = info,CREATE
log4j.logger.net.network.client.C_CharacterDelete = info,DELETE
log4j.logger.net.world.function.MonthCardsSystem = info,CARDS
log4j.logger.net.world.instance.ItemMagicInstance = info,SKILL
log4j.logger.net.world.instance.skill.PcSkill = info,SKILL
log4j.logger.net.world.npc.Ellyonne = info,SKILL
log4j.logger.net.LineageProtocolHandler = info,NETWORK
log4j.logger.net.mina.LineagePacketDecoder = info,PACKET_DECODER
log4j.logger.net.world.time.LoginTimer = info,LOGIN_VERIFICATION
log4j.logger.net.ConsoleProcess = info,CP
log4j.logger.com.mchange = warn
log4j.logger.org.apache.mina = warn
log4j.logger.net.mina.LineageBlackListFilter = error,NETWORK
log4j.logger.net.mina.LineageConnectionThrottleFilter = error,NETWORK

##################### 聊天
log4j.appender.CHAT = org.apache.log4j.DailyRollingFileAppender
log4j.appender.CHAT.File = log/Chat.txt
log4j.appender.CHAT.Append = true
log4j.appender.CHAT.Threshold = debug
log4j.appender.CHAT.layout = org.apache.log4j.PatternLayout
log4j.appender.CHAT.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n

##################### 交易日誌
#log4j.appender.TRADE = org.apache.log4j.DailyRollingFileAppender
#log4j.appender.TRADE.File = log/Trade.txt
#log4j.appender.TRADE.Append = true
#log4j.appender.TRADE.Threshold = debug
#log4j.appender.TRADE.layout = org.apache.log4j.PatternLayout
#log4j.appender.TRADE.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n

##################### 強化日誌
#log4j.appender.ENCHANT = org.apache.log4j.DailyRollingFileAppender
#log4j.appender.ENCHANT.File = log/Enchant.txt
#log4j.appender.ENCHANT.Append = true
#log4j.appender.ENCHANT.Threshold = debug
#log4j.appender.ENCHANT.layout = org.apache.log4j.PatternLayout
#log4j.appender.ENCHANT.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n

##################### 掉落日誌
#log4j.appender.MON_DROP_DOWN = org.apache.log4j.DailyRollingFileAppender
#log4j.appender.MON_DROP_DOWN.File = log/MonDropDown.txt
#log4j.appender.MON_DROP_DOWN.Append = true
#log4j.appender.MON_DROP_DOWN.Threshold = debug
#log4j.appender.MON_DROP_DOWN.layout = org.apache.log4j.PatternLayout
#log4j.appender.MON_DROP_DOWN.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n

##################### 所有物品日誌 包括 怪物掉落、商店購買銷售、扔地面、強化、存取倉庫、交易
log4j.appender.ITEM = org.apache.log4j.DailyRollingFileAppender
log4j.appender.ITEM.File = log/ItemALL.txt
log4j.appender.ITEM.Append = true
log4j.appender.ITEM.Threshold = debug
log4j.appender.ITEM.layout = org.apache.log4j.PatternLayout
log4j.appender.ITEM.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n

##################### 加速日誌
log4j.appender.SPEED = org.apache.log4j.DailyRollingFileAppender
log4j.appender.SPEED.File = log/Speed.txt
log4j.appender.SPEED.Append = true
log4j.appender.SPEED.Threshold = debug
log4j.appender.SPEED.layout = org.apache.log4j.PatternLayout
log4j.appender.SPEED.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n

##################### 賬號登陸、登陸出
log4j.appender.LOGINOUT = org.apache.log4j.DailyRollingFileAppender
log4j.appender.LOGINOUT.File = log/LoginOut.txt
log4j.appender.LOGINOUT.Append = true
log4j.appender.LOGINOUT.Threshold = debug
log4j.appender.LOGINOUT.layout = org.apache.log4j.PatternLayout
log4j.appender.LOGINOUT.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n

##################### 角色創建
log4j.appender.CREATE = org.apache.log4j.DailyRollingFileAppender
log4j.appender.CREATE.File = log/CharacterCreate.txt
log4j.appender.CREATE.Append = true
log4j.appender.CREATE.Threshold = debug
log4j.appender.CREATE.layout = org.apache.log4j.PatternLayout
log4j.appender.CREATE.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n

##################### 角色刪除
log4j.appender.DELETE = org.apache.log4j.DailyRollingFileAppender
log4j.appender.DELETE.File = log/CharacterDelete.txt
log4j.appender.DELETE.Append = true
log4j.appender.DELETE.Threshold = debug
log4j.appender.DELETE.layout = org.apache.log4j.PatternLayout
log4j.appender.DELETE.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n

### 輸出到控制台 (因輸出到控制台對性能影響非常大，一般的會將日誌級別調高)###
log4j.appender.STDOUT = org.apache.log4j.ConsoleAppender
log4j.appender.STDOUT.Target = System.out
log4j.appender.STDOUT.Threshold = warn
log4j.appender.STDOUT.layout = org.apache.log4j.PatternLayout
log4j.appender.STDOUT.layout.ConversionPattern =  %d{ABSOLUTE} %5p %c{1}:%L - %m%n

### 輸出到日誌文件 DEBUG ###
#log4j.appender.D = org.apache.log4j.RollingFileAppender
#log4j.appender.D.MaxFileSize =50000KB
#log4j.appender.D.File = log/debug.txt
#log4j.appender.D.Append = true
#log4j.appender.D.Threshold = debug
#log4j.appender.D.layout = org.apache.log4j.PatternLayout
#log4j.appender.D.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} [ %t:%r ] - [ %p ]  %m%n

### 保存異常信息到單獨文件 ###
log4j.appender.E = org.apache.log4j.DailyRollingFileAppender
log4j.appender.E.File = log/error.txt
log4j.appender.E.Append = true
log4j.appender.E.Threshold = error
log4j.appender.E.layout = org.apache.log4j.PatternLayout
log4j.appender.E.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} [ %t:%r ] - [ %p ]  %m%n

##################### 月卡
log4j.appender.CARDS = org.apache.log4j.DailyRollingFileAppender
log4j.appender.CARDS.File = log/MonthCards.txt
log4j.appender.CARDS.Append = true
log4j.appender.CARDS.Threshold = debug
log4j.appender.CARDS.layout = org.apache.log4j.PatternLayout
log4j.appender.CARDS.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n

##################### 技能(學習、刪除)
log4j.appender.SKILL = org.apache.log4j.DailyRollingFileAppender
log4j.appender.SKILL.File = log/skill.txt
log4j.appender.SKILL.Append = true
log4j.appender.SKILL.Threshold = debug
log4j.appender.SKILL.layout = org.apache.log4j.PatternLayout
log4j.appender.SKILL.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n

##################### 網絡相關
log4j.appender.NETWORK = org.apache.log4j.DailyRollingFileAppender
log4j.appender.NETWORK.File = log/network/Fi.txt
log4j.appender.NETWORK.Append = true
log4j.appender.NETWORK.Threshold = debug
log4j.appender.NETWORK.layout = org.apache.log4j.PatternLayout
log4j.appender.NETWORK.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n

##################### 網絡相關(封包解密)
log4j.appender.PACKET_DECODER = org.apache.log4j.DailyRollingFileAppender
log4j.appender.PACKET_DECODER.File = log/network/PacketDecoder.txt
log4j.appender.PACKET_DECODER.Append = true
log4j.appender.PACKET_DECODER.Threshold = debug
log4j.appender.PACKET_DECODER.layout = org.apache.log4j.PatternLayout
log4j.appender.PACKET_DECODER.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n

##################### 登陸器相關
log4j.appender.LOGIN_VERIFICATION = org.apache.log4j.DailyRollingFileAppender
log4j.appender.LOGIN_VERIFICATION.File = log/LoginVerification.txt
log4j.appender.LOGIN_VERIFICATION.Append = true
log4j.appender.LOGIN_VERIFICATION.Threshold = debug
log4j.appender.LOGIN_VERIFICATION.layout = org.apache.log4j.PatternLayout
log4j.appender.LOGIN_VERIFICATION.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n

##################### CMD 互動命令 處理程序
log4j.appender.CP = org.apache.log4j.DailyRollingFileAppender
log4j.appender.CP.File = log/ConsoleProcess.txt
log4j.appender.CP.Append = true
log4j.appender.CP.Threshold = debug
log4j.appender.CP.layout = org.apache.log4j.PatternLayout
log4j.appender.CP.layout.ConversionPattern = %-d{MM-dd HH:mm:ss} %m%n