#-------------------------------------------------------------
# 所有設定
#-------------------------------------------------------------

# 數據庫驅動程序
Driver = com.mysql.jdbc.Driver

# 數據庫路徑、名稱與字符編碼
URL = jdbc:mysql://127.0.0.1/182?useUnicode=true&zeroDateTimeBehavior=round&characterEncoding=utf8

# 數據庫賬號
Login = root

# 數據庫密碼
Password = 0423


# 客戶端語言 0.美國 3.台灣 5.大陸
ClientLanguage = 3

# 經驗
RateXp=10
# 金幣
RateDropAdena=1
# 強化
EnchantChance=1
# 掉落
RateDropItems=1

# 自動創建賬號
AutoCreateAccounts=True
GameserverPort=2000

#調試模式
DebugMode=False

# 掉落設置 0地上 1身上
AutoLoot=1

# 法師瑪那任務
QuestWizardManaLevel=15

# 變身活動
EventPolyScroll=True

# 刪除地面物品 分鐘數
ALT_ITEM_DELETION_TIME=60

###############防加速系統########################

# 防加速類型(1.原先的判斷 2.新的判斷) - 兩個不能同時存在
checkSpeedType = 2

# 加速器打印日誌
DebugSpeedPrint=False
# 加速器提示玩家
SPEED_MESSAGE=False

#----------類型(1)---------------

# 加速達到N次後處罰
ATTACK_COUNT=6
MOVE_COUNT=8
MAGIC_COUNT=4

# 惡意加速達到N次後斷線
SPEED_HACK=3

# 輕微加速
# 倍數
SPEED_1=1.3
# 是否處罰
SPEED_1_PUN=False

# 惡意加速
SPEED_2=1.6
SPEED_2_PUN=False

#----------類型(2)---------------

# 檢查密度(如果誤報率大就稍微調大)
CheckStrictness = 120

# 加速處罰機制(0.冰凍 1.傳送回原坐標 2.踢出遊戲)
Punishment = 1

#######################################

#狗狗死亡後多久消失 (秒)
PET_TO_DEAT_TIME=600

# 最高級別
LEVEL_MAX=90


# 王族最高血量
RoyalMaxHP = 1400
# 王族最高魔量
RoyalMaxMP = 800
# 騎士最高血量
KnightMaxHP = 2000
# 騎士最高魔量
KnightMaxMP = 600
# 精靈最高血量
ElfMaxHP = 1400
# 精靈最高魔量
ElfMaxMP = 900
# 法師最高血量
WizardMaxHP = 1000
# 法師最高魔量
WizardMaxMP = 1200

# 是否顯示NpcId
SHOW_NPC_ID = False

# 角色是否能看到自己血條
showOwHpBar = False
# 廣播自己血量給周圍
broadcastHpToAround = False

# 是否開啟月卡模式(如果打開則必須充值才能繼續遊戲)
openRecharge = False

# 新人贈送的免費時間(月卡模式有效、單位：分鐘)
newTalentTime = 3

# 服務器重啟(按照現實時間/單位：小時[24小時制]) 例如：5就表示每天的5點1分重啟【如果是25則關閉自動重啟】
restartTime = 25

#組隊經驗加成方式. (1:固定倍率，2每多一隊友加倍率)
partyExpType = 1
#組隊經驗加成
ratePartyExp = 0.2

# 粉名 true or false
pinkName = true 

# BOSS是否開機出現(false為不出現)
boss = False

# 是否顯示組隊吸寶提示(true為顯示)
partyMessage = False

# 玩家PK玩家時的物理防禦減傷(被攻擊對象的物理防禦值 / 設置的值)【數值越大 傷害越高 最低1】
# 0為關閉該功能
reduceInjuryAc = 8

# 是否開啟史萊姆競技場(False為關閉)
Slime = true
# 史萊姆競技場單次比賽間隔時間(分鐘)
SlimeTime = 5

# 角色負重倍率
# RateWeightLimit 0.0-127.0
RateWeightLimit = 3.0