#-------------------------------------------------------------
# HTML文件相關
#-------------------------------------------------------------

# 是否開啟寫入在線總人數功能
isOnline = false

# 間隔時間(秒)
onlineTime = 2

# 在線總人數HTML文件路徑(相對、絕對路徑都行)【帶文件後綴名】
onlineUrl = C:/test.html

# 是否開啟寫入在線角色功能
isOnlinePc = false

# 間隔時間(秒)
onlineTimePc = 2

# 在線角色HTML文件路徑(相對、絕對路徑都行)【帶文件後綴名】
onlineUrlPc = c:/testPc.html