#-------------------------------------------------------------
# 登陸器相關
#-------------------------------------------------------------

# 服務器最大人數
maxAmount = 100

---------------
lv = 1
no = 1
---------------

# 登陸器驗證
loginVerification = False

# 驗證間隔時間(不要低於2分鐘、單位:分鐘)
loginTimer = 3
