#-------------------------------------------------------------
# 測試設定
# 【注意 正式開必須關閉此文件內的所有功能】
#-------------------------------------------------------------

# 測試1(召喚 阿魯巴)
test = false

# 測試2(顯示玩家物理攻擊命中率)
testHit = false

# 測試3(顯示玩家PK時的物理攻擊傷害值)
testReduceInjuryAc = false