/*
MySQL Data Transfer
Source Host: localhost
Source Database: lineage
Target Host: localhost
Target Database: lineage
Date: 2014/8/7 9:28:45
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for sprite_frame
-- ----------------------------
CREATE TABLE `sprite_frame` (
  `name` varchar(255) NOT NULL DEFAULT '',
  `gfx` int(10) unsigned NOT NULL DEFAULT '0',
  `action` int(10) unsigned NOT NULL DEFAULT '0',
  `action_name` varchar(255) NOT NULL DEFAULT '',
  `frame` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`gfx`,`action`),
  KEY `id` (`gfx`),
  KEY `type` (`name`)
) ENGINE=MyISAM AUTO_INCREMENT=388 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `sprite_frame` VALUES ('王子', '0', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('王子', '0', '1', 'attack', '840');
INSERT INTO `sprite_frame` VALUES ('王子', '0', '4', 'walk sword', '640');
INSERT INTO `sprite_frame` VALUES ('王子', '0', '5', 'attack sword', '1000');
INSERT INTO `sprite_frame` VALUES ('王子', '0', '11', 'walk axe', '640');
INSERT INTO `sprite_frame` VALUES ('王子', '0', '12', 'attack axe', '880');
INSERT INTO `sprite_frame` VALUES ('王子', '0', '20', 'walk bow', '640');
INSERT INTO `sprite_frame` VALUES ('王子', '0', '21', 'attack bow', '1600');
INSERT INTO `sprite_frame` VALUES ('王子', '0', '24', 'walk Spear', '640');
INSERT INTO `sprite_frame` VALUES ('王子', '0', '25', 'attack Spear', '880');
INSERT INTO `sprite_frame` VALUES ('王子', '0', '18', 'spell direction', '880');
INSERT INTO `sprite_frame` VALUES ('王子', '0', '19', 'spell no direction', '800');
INSERT INTO `sprite_frame` VALUES ('王子', '0', '40', 'walk staff', '640');
INSERT INTO `sprite_frame` VALUES ('王子', '0', '41', 'attack staff', '880');
INSERT INTO `sprite_frame` VALUES ('公主', '1', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('公主', '1', '1', 'attack', '880');
INSERT INTO `sprite_frame` VALUES ('公主', '1', '4', 'walk sword', '640');
INSERT INTO `sprite_frame` VALUES ('公主', '1', '5', 'attack sword', '960');
INSERT INTO `sprite_frame` VALUES ('公主', '1', '11', 'walk axe', '640');
INSERT INTO `sprite_frame` VALUES ('公主', '1', '12', 'attack axe', '1000');
INSERT INTO `sprite_frame` VALUES ('公主', '1', '20', 'walk bow', '640');
INSERT INTO `sprite_frame` VALUES ('公主', '1', '21', 'attack bow', '1520');
INSERT INTO `sprite_frame` VALUES ('公主', '1', '24', 'walk spear', '640');
INSERT INTO `sprite_frame` VALUES ('公主', '1', '25', 'attack spear', '1040');
INSERT INTO `sprite_frame` VALUES ('公主', '1', '18', 'spell direction', '880');
INSERT INTO `sprite_frame` VALUES ('公主', '1', '19', 'spell no direction', '800');
INSERT INTO `sprite_frame` VALUES ('公主', '1', '40', 'walk staff', '640');
INSERT INTO `sprite_frame` VALUES ('公主', '1', '41', 'attack staff', '1000');
INSERT INTO `sprite_frame` VALUES ('漂浮之眼', '29', '0', 'move', '960');
INSERT INTO `sprite_frame` VALUES ('漂浮之眼', '29', '1', 'attack', '1720');
INSERT INTO `sprite_frame` VALUES ('漂浮之眼', '29', '19', 'spell no dir', '1720');
INSERT INTO `sprite_frame` VALUES ('骷髏', '30', '1', 'attack', '920');
INSERT INTO `sprite_frame` VALUES ('骷髏', '30', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('骷髏', '30', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('骷髏', '30', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('長者', '32', '0', 'move', '960');
INSERT INTO `sprite_frame` VALUES ('長者', '32', '1', 'attack', '1800');
INSERT INTO `sprite_frame` VALUES ('長者', '32', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('長者', '32', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('女妖精', '37', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('女妖精', '37', '1', 'attack', '800');
INSERT INTO `sprite_frame` VALUES ('女妖精', '37', '4', 'walk sword', '640');
INSERT INTO `sprite_frame` VALUES ('女妖精', '37', '5', 'attack sword', '760');
INSERT INTO `sprite_frame` VALUES ('女妖精', '37', '11', 'walk axe', '640');
INSERT INTO `sprite_frame` VALUES ('女妖精', '37', '12', 'attack axe', '1120');
INSERT INTO `sprite_frame` VALUES ('女妖精', '37', '18', 'spell dir', '880');
INSERT INTO `sprite_frame` VALUES ('女妖精', '37', '19', 'spell nodir', '800');
INSERT INTO `sprite_frame` VALUES ('女妖精', '37', '20', 'walk bow', '640');
INSERT INTO `sprite_frame` VALUES ('女妖精', '37', '21', 'attack bow', '960');
INSERT INTO `sprite_frame` VALUES ('女妖精', '37', '24', 'walk spear', '640');
INSERT INTO `sprite_frame` VALUES ('女妖精', '37', '25', 'attack spear', '1120');
INSERT INTO `sprite_frame` VALUES ('女妖精', '37', '40', 'walk staff', '640');
INSERT INTO `sprite_frame` VALUES ('女妖精', '37', '41', 'attack staff', '920');
INSERT INTO `sprite_frame` VALUES ('女騎士', '48', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('女騎士', '48', '1', 'attack', '1000');
INSERT INTO `sprite_frame` VALUES ('女騎士', '48', '4', 'walk sword', '640');
INSERT INTO `sprite_frame` VALUES ('女騎士', '48', '5', 'attack sword', '920');
INSERT INTO `sprite_frame` VALUES ('女騎士', '48', '11', 'walk axe', '640');
INSERT INTO `sprite_frame` VALUES ('女騎士', '48', '12', 'attack axe', '920');
INSERT INTO `sprite_frame` VALUES ('女騎士', '48', '18', 'spell dir', '800');
INSERT INTO `sprite_frame` VALUES ('女騎士', '48', '19', 'spell nodir', '800');
INSERT INTO `sprite_frame` VALUES ('女騎士', '48', '20', 'walk bow', '640');
INSERT INTO `sprite_frame` VALUES ('女騎士', '48', '21', 'attack bow', '1840');
INSERT INTO `sprite_frame` VALUES ('女騎士', '48', '24', 'walk spear', '640');
INSERT INTO `sprite_frame` VALUES ('女騎士', '48', '25', 'attack spear', '1000');
INSERT INTO `sprite_frame` VALUES ('女騎士', '48', '40', 'walk staff', '640');
INSERT INTO `sprite_frame` VALUES ('女騎士', '48', '41', 'attack staff', '920');
INSERT INTO `sprite_frame` VALUES ('高侖石頭怪', '49', '0', 'walk', '1280');
INSERT INTO `sprite_frame` VALUES ('高侖石頭怪', '49', '1', 'attack', '1920');
INSERT INTO `sprite_frame` VALUES ('高侖石頭怪', '49', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('高侖石頭怪', '49', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('人形僵屍', '52', '0', 'walk', '1640');
INSERT INTO `sprite_frame` VALUES ('人形僵屍', '52', '1', 'attack', '1040');
INSERT INTO `sprite_frame` VALUES ('人形僵屍', '52', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('人形僵屍', '52', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('巴風特', '53', '0', 'walk', '480');
INSERT INTO `sprite_frame` VALUES ('巴風特', '53', '1', 'attack', '840');
INSERT INTO `sprite_frame` VALUES ('巴風特', '53', '18', 'spell direction', '880');
INSERT INTO `sprite_frame` VALUES ('侏儒', '54', '0', 'walk', '560');
INSERT INTO `sprite_frame` VALUES ('侏儒', '54', '1', 'attack', '1480');
INSERT INTO `sprite_frame` VALUES ('侏儒', '54', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('侏儒', '54', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('妖魔', '56', '0', 'walk', '800');
INSERT INTO `sprite_frame` VALUES ('妖魔', '56', '1', 'attack', '1320');
INSERT INTO `sprite_frame` VALUES ('妖魔', '56', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('妖魔', '56', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('妖魔弓箭手', '57', '20', 'walk bow', '800');
INSERT INTO `sprite_frame` VALUES ('妖魔弓箭手', '57', '21', 'attack bow', '1160');
INSERT INTO `sprite_frame` VALUES ('妖魔弓箭手', '57', '19', 'spellnd', '680');
INSERT INTO `sprite_frame` VALUES ('妖魔弓箭手', '57', '18', 'spell', '720');
INSERT INTO `sprite_frame` VALUES ('男騎士', '61', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('男騎士', '61', '1', 'attack', '880');
INSERT INTO `sprite_frame` VALUES ('男騎士', '61', '4', 'walk sword', '640');
INSERT INTO `sprite_frame` VALUES ('男騎士', '61', '5', 'attack sword', '880');
INSERT INTO `sprite_frame` VALUES ('男騎士', '61', '11', 'walk axe', '640');
INSERT INTO `sprite_frame` VALUES ('男騎士', '61', '12', 'attack axe', '880');
INSERT INTO `sprite_frame` VALUES ('男騎士', '61', '18', 'spell dir', '880');
INSERT INTO `sprite_frame` VALUES ('男騎士', '61', '19', 'spell nodir', '800');
INSERT INTO `sprite_frame` VALUES ('男騎士', '61', '20', 'walk bow', '640');
INSERT INTO `sprite_frame` VALUES ('男騎士', '61', '21', 'attack bow', '1920');
INSERT INTO `sprite_frame` VALUES ('男騎士', '61', '24', 'walk spear', '640');
INSERT INTO `sprite_frame` VALUES ('男騎士', '61', '25', 'attack spear', '920');
INSERT INTO `sprite_frame` VALUES ('男騎士', '61', '40', 'walk staff', '640');
INSERT INTO `sprite_frame` VALUES ('男騎士', '61', '41', 'attack staff', '880');
INSERT INTO `sprite_frame` VALUES ('妖魔鬥士', '94', '4', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('妖魔鬥士', '94', '5', 'attack sword', '920');
INSERT INTO `sprite_frame` VALUES ('妖魔鬥士', '94', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('妖魔鬥士', '94', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('夏洛伯', '95', '0', 'walk', '480');
INSERT INTO `sprite_frame` VALUES ('夏洛伯', '95', '1', 'attack', '880');
INSERT INTO `sprite_frame` VALUES ('夏洛伯', '95', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('夏洛伯', '95', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('狼', '96', '0', 'walk', '480');
INSERT INTO `sprite_frame` VALUES ('狼', '96', '1', 'attack', '1320');
INSERT INTO `sprite_frame` VALUES ('狼', '96', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('狼', '96', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('男妖精', '138', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('男妖精', '138', '1', 'attack', '760');
INSERT INTO `sprite_frame` VALUES ('男妖精', '138', '4', 'walk Sword', '640');
INSERT INTO `sprite_frame` VALUES ('男妖精', '138', '5', 'attack Sword', '800');
INSERT INTO `sprite_frame` VALUES ('男妖精', '138', '11', 'walk Axe', '640');
INSERT INTO `sprite_frame` VALUES ('男妖精', '138', '12', 'attack Axe', '1040');
INSERT INTO `sprite_frame` VALUES ('男妖精', '138', '18', 'Spell Direction', '880');
INSERT INTO `sprite_frame` VALUES ('男妖精', '138', '19', 'Spell No Direction', '800');
INSERT INTO `sprite_frame` VALUES ('男妖精', '138', '20', 'walk Bow', '640');
INSERT INTO `sprite_frame` VALUES ('男妖精', '138', '21', 'attack bow', '960');
INSERT INTO `sprite_frame` VALUES ('男妖精', '138', '24', 'walk Spear', '640');
INSERT INTO `sprite_frame` VALUES ('男妖精', '138', '25', 'attack Spear', '1080');
INSERT INTO `sprite_frame` VALUES ('男妖精', '138', '40', 'walk staff', '640');
INSERT INTO `sprite_frame` VALUES ('男妖精', '138', '41', 'attack staff', '920');
INSERT INTO `sprite_frame` VALUES ('食屍鬼', '144', '0', 'walk', '1280');
INSERT INTO `sprite_frame` VALUES ('食屍鬼', '144', '1', 'attack', '720');
INSERT INTO `sprite_frame` VALUES ('食屍鬼', '144', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('食屍鬼', '144', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('史巴托', '145', '0', 'walk', '800');
INSERT INTO `sprite_frame` VALUES ('史巴托', '145', '1', 'attack', '920');
INSERT INTO `sprite_frame` VALUES ('史巴托', '145', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('史巴托', '145', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('楊果裡恩', '146', '0', 'walk', '480');
INSERT INTO `sprite_frame` VALUES ('楊果裡恩', '146', '1', 'attack', '840');
INSERT INTO `sprite_frame` VALUES ('楊果裡恩', '146', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('楊果裡恩', '146', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('食人妖精', '152', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('食人妖精', '152', '1', 'attack', '840');
INSERT INTO `sprite_frame` VALUES ('食人妖精', '152', '18', 'spell direction', '880');
INSERT INTO `sprite_frame` VALUES ('食人妖精', '152', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('卡士伯', '173', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('卡士伯', '173', '1', 'attack', '1480');
INSERT INTO `sprite_frame` VALUES ('黑長者(西瑪)', '183', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('黑長者(西瑪)', '183', '1', 'attack', '1480');
INSERT INTO `sprite_frame` VALUES ('黑長者(西瑪)', '183', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('巴士瑟', '185', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('巴士瑟', '185', '1', 'attack', '1480');
INSERT INTO `sprite_frame` VALUES ('馬庫爾', '187', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('馬庫爾', '187', '1', 'attack', '1480');
INSERT INTO `sprite_frame` VALUES ('死亡騎士', '240', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('死亡騎士', '240', '1', 'attack', '600');
INSERT INTO `sprite_frame` VALUES ('死亡騎士', '240', '18', 'Spell Direction', '880');
INSERT INTO `sprite_frame` VALUES ('死亡騎士', '240', '19', 'Spell No Direction', '800');
INSERT INTO `sprite_frame` VALUES ('卡司特', '255', '0', 'Walk', '1080');
INSERT INTO `sprite_frame` VALUES ('卡司特', '255', '1', 'Aattak', '640');
INSERT INTO `sprite_frame` VALUES ('卡司特', '255', '19', 'spellnd', '760');
INSERT INTO `sprite_frame` VALUES ('卡司特', '255', '18', 'spell', '760');
INSERT INTO `sprite_frame` VALUES ('男法師', '734', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('男法師', '734', '1', 'attack', '960');
INSERT INTO `sprite_frame` VALUES ('男法師', '734', '4', 'walk sword', '640');
INSERT INTO `sprite_frame` VALUES ('男法師', '734', '5', 'attack sword', '1120');
INSERT INTO `sprite_frame` VALUES ('男法師', '734', '11', 'walk Axe', '640');
INSERT INTO `sprite_frame` VALUES ('男法師', '734', '12', 'attack Axe', '1040');
INSERT INTO `sprite_frame` VALUES ('男法師', '734', '18', 'Spell Direction', '880');
INSERT INTO `sprite_frame` VALUES ('男法師', '734', '19', 'Spell No Direction', '800');
INSERT INTO `sprite_frame` VALUES ('男法師', '734', '20', 'walk Bow', '640');
INSERT INTO `sprite_frame` VALUES ('男法師', '734', '21', 'attack bow', '2280');
INSERT INTO `sprite_frame` VALUES ('男法師', '734', '24', 'walk Spear', '640');
INSERT INTO `sprite_frame` VALUES ('男法師', '734', '25', 'attack Spear', '1200');
INSERT INTO `sprite_frame` VALUES ('男法師', '734', '40', 'walk staff', '640');
INSERT INTO `sprite_frame` VALUES ('男法師', '734', '41', 'attack staff', '1200');
INSERT INTO `sprite_frame` VALUES ('甘地妖魔(羅浮)', '784', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('甘地妖魔(羅浮)', '784', '1', 'attack', '1040');
INSERT INTO `sprite_frame` VALUES ('甘地妖魔(羅浮)', '784', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('甘地妖魔(羅浮)', '784', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('阿吐巴妖魔', '786', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('都達瑪拉妖魔(那魯加)', '788', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('食人妖精王', '894', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('食人妖精王', '894', '1', 'attack', '840');
INSERT INTO `sprite_frame` VALUES ('食人妖精王', '894', '18', 'spell direction', '880');
INSERT INTO `sprite_frame` VALUES ('食人妖精王', '894', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('聖伯納犬', '929', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('聖伯納犬', '929', '1', 'attack', '1440');
INSERT INTO `sprite_frame` VALUES ('杜賓狗', '931', '0', 'walk', '480');
INSERT INTO `sprite_frame` VALUES ('杜賓狗', '931', '1', 'attack', '880');
INSERT INTO `sprite_frame` VALUES ('柯利', '934', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('柯利', '934', '1', 'attack', '720');
INSERT INTO `sprite_frame` VALUES ('牧羊犬', '936', '0', 'walk', '480');
INSERT INTO `sprite_frame` VALUES ('牧羊犬', '936', '1', 'attack', '960');
INSERT INTO `sprite_frame` VALUES ('小獵犬', '938', '0', 'walk', '480');
INSERT INTO `sprite_frame` VALUES ('小獵犬', '938', '1', 'attack', '800');
INSERT INTO `sprite_frame` VALUES ('奶牛', '945', '0', 'walk', '1920');
INSERT INTO `sprite_frame` VALUES ('鹿', '947', '0', 'walk', '1280');
INSERT INTO `sprite_frame` VALUES ('地獄犬', '951', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('地獄犬', '951', '1', 'attack', '1040');
INSERT INTO `sprite_frame` VALUES ('野豬', '979', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('野豬', '979', '1', 'attack', '800');
INSERT INTO `sprite_frame` VALUES ('巴列斯', '1011', '0', 'walk', '480');
INSERT INTO `sprite_frame` VALUES ('巴列斯', '1011', '1', 'attack', '840');
INSERT INTO `sprite_frame` VALUES ('巴列斯', '1011', '18', 'spell direction', '880');
INSERT INTO `sprite_frame` VALUES ('歐吉', '1020', '0', 'walk', '960');
INSERT INTO `sprite_frame` VALUES ('歐吉', '1020', '1', 'attack', '1320');
INSERT INTO `sprite_frame` VALUES ('歐吉', '1020', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('歐吉', '1020', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('哥布林', '1022', '0', 'walk', '760');
INSERT INTO `sprite_frame` VALUES ('哥布林', '1022', '1', 'attack', '920');
INSERT INTO `sprite_frame` VALUES ('哥布林', '1022', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('哥布林', '1022', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('巨蟻', '1037', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('巨蟻', '1037', '1', 'attack', '880');
INSERT INTO `sprite_frame` VALUES ('巨大兵蟻', '1039', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('巨大兵蟻', '1039', '1', 'attack', '760');
INSERT INTO `sprite_frame` VALUES ('毒蝎', '1047', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('毒蝎', '1047', '1', 'attack', '800');
INSERT INTO `sprite_frame` VALUES ('亞力安', '1052', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('亞力安', '1052', '1', 'attack', '1040');
INSERT INTO `sprite_frame` VALUES ('亞力安', '1052', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('地靈', '1059', '0', 'walk', '1280');
INSERT INTO `sprite_frame` VALUES ('地靈', '1059', '1', 'attack', '1080');
INSERT INTO `sprite_frame` VALUES ('地靈', '1059', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('地靈', '1059', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('骷髏弓箭手', '1096', '0', 'walk bow', '800');
INSERT INTO `sprite_frame` VALUES ('骷髏弓箭手', '1096', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('骷髏弓箭手', '1096', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('骷髏弓箭手', '1096', '1', 'attack bow', '1120');
INSERT INTO `sprite_frame` VALUES ('多羅', '1098', '0', 'walk', '960');
INSERT INTO `sprite_frame` VALUES ('多羅', '1098', '1', 'attack', '1280');
INSERT INTO `sprite_frame` VALUES ('多羅', '1098', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('多羅', '1098', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('骷髏斧手', '1104', '0', 'walk', '480');
INSERT INTO `sprite_frame` VALUES ('骷髏斧手', '1104', '1', 'attack', '840');
INSERT INTO `sprite_frame` VALUES ('骷髏斧手', '1104', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('骷髏斧手', '1104', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('骷髏槍兵', '1106', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('骷髏槍兵', '1106', '1', 'attack', '880');
INSERT INTO `sprite_frame` VALUES ('骷髏槍兵', '1106', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('骷髏槍兵', '1106', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('萊肯', '1108', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('萊肯', '1108', '1', 'attack', '880');
INSERT INTO `sprite_frame` VALUES ('萊肯', '1108', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('萊肯', '1108', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('狼人', '1110', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('狼人', '1110', '1', 'attack', '840');
INSERT INTO `sprite_frame` VALUES ('狼人', '1110', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('狼人', '1110', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('黑暗精靈', '1125', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('黑暗精靈', '1125', '1', 'attack', '1000');
INSERT INTO `sprite_frame` VALUES ('黑暗精靈', '1125', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('阿魯巴', '1128', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('阿魯巴', '1128', '1', 'attack', '1160');
INSERT INTO `sprite_frame` VALUES ('惡魔', '1180', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('惡魔', '1180', '1', 'attack', '960');
INSERT INTO `sprite_frame` VALUES ('惡魔', '1180', '18', 'spell', '880');
INSERT INTO `sprite_frame` VALUES ('女法師', '1186', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('女法師', '1186', '1', 'attack', '1000');
INSERT INTO `sprite_frame` VALUES ('女法師', '1186', '4', 'walk sword', '640');
INSERT INTO `sprite_frame` VALUES ('女法師', '1186', '5', 'attack sword', '1120');
INSERT INTO `sprite_frame` VALUES ('女法師', '1186', '11', 'walk Axe', '640');
INSERT INTO `sprite_frame` VALUES ('女法師', '1186', '12', 'attack Axe', '1080');
INSERT INTO `sprite_frame` VALUES ('女法師', '1186', '18', 'Spell Direction', '880');
INSERT INTO `sprite_frame` VALUES ('女法師', '1186', '19', 'Spell No Direction', '800');
INSERT INTO `sprite_frame` VALUES ('女法師', '1186', '20', 'walk Bow', '640');
INSERT INTO `sprite_frame` VALUES ('女法師', '1186', '21', 'attack bow', '2240');
INSERT INTO `sprite_frame` VALUES ('女法師', '1186', '24', 'walk Spear', '640');
INSERT INTO `sprite_frame` VALUES ('女法師', '1186', '25', 'attack Spear', '1160');
INSERT INTO `sprite_frame` VALUES ('女法師', '1186', '40', 'walk staff', '640');
INSERT INTO `sprite_frame` VALUES ('女法師', '1186', '41', 'attack staff', '1160');
INSERT INTO `sprite_frame` VALUES ('獨眼巨人', '1202', '0', 'walk', '960');
INSERT INTO `sprite_frame` VALUES ('獨眼巨人', '1202', '1', 'attack', '1160');
INSERT INTO `sprite_frame` VALUES ('格利芬', '1204', '0', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('格利芬', '1204', '1', 'attack', '1280');
INSERT INTO `sprite_frame` VALUES ('妖魔巡守', '2323', '20', 'walk', '640');
INSERT INTO `sprite_frame` VALUES ('妖魔巡守', '2323', '21', 'attack', '1000');
INSERT INTO `sprite_frame` VALUES ('妖魔巡守', '2323', '19', 'spellnd', '800');
INSERT INTO `sprite_frame` VALUES ('妖魔巡守', '2323', '18', 'spell', '880');
